version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=siakad
    volumes:
      - .:/var/www/html
      - ./images:/var/www/html/images
      - ./foto_gp:/var/www/html/foto_gp
      - ./foto_kegiatan:/var/www/html/foto_kegiatan
      - ./foto_santri:/var/www/html/foto_santri
      - ./apache.conf:/etc/apache2/httpd.conf
    depends_on:
      - db
    networks:
      - siakad_network
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=siakad
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump-old_siakad-202503071150.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - siakad_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  siakad_network:
    driver: bridge

